# Generated by Django 6.0.7 on 2026-07-12 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.CharField(blank=True, max_length=10, null=True)),
                ('course', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.CharField(blank=True, max_length=10, null=True)),
                ('goals', models.JSONField(blank=True, default=list)),
                ('study_time', models.CharField(blank=True, max_length=50, null=True)),
                ('study_hours', models.IntegerField(default=0)),
                ('study_days', models.IntegerField(default=0)),
                ('challenges', models.JSONField(blank=True, default=list)),
                ('habits', models.JSONField(blank=True, default=list)),
                ('motivation', models.TextField(blank=True, max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
