# Generated by Django 5.2.16 on 2026-07-14 14:38

import django.core.validators
import profiles.models
import profiles.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_migrate_legacy_behavior_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='goals',
            field=models.JSONField(blank=True, default=list, help_text='Legacy onboarding data; use goals.Goal for new records.'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='habits',
            field=models.JSONField(blank=True, default=list, help_text='Legacy onboarding data; use habits.Habit for new records.'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='study_days',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='study_weekdays',
            field=models.JSONField(default=profiles.models.default_study_weekdays, validators=[profiles.validators.validate_iso_weekdays]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='timezone',
            field=models.CharField(default='UTC', max_length=64, validators=[profiles.validators.validate_iana_timezone]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
