# Generated by Django 5.2.16 on 2026-07-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_journalentry_ai_opt_out_journalaiconsent'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalaiconsent',
            name='provider_policy_version',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='journalaiconsent',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
