# Generated by Django 6.0.7 on 2026-07-13 07:48

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField(default=django.utils.timezone.localdate, editable=False)),
                ('study_hours', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(8)])),
                ('planned_study_status', models.CharField(choices=[('complete', 'Yes, completely'), ('partial', 'Partially'), ('not_today', 'Not today')], max_length=20)),
                ('focus_level', models.CharField(choices=[('deep_focus', 'Deep Focus'), ('mostly_focused', 'Mostly Focused'), ('average', 'Average'), ('frequently_distracted', 'Often Distracted'), ('could_not_focus', "Couldn't Focus")], max_length=30)),
                ('mood', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('okay', 'Okay'), ('low', 'Low'), ('stressed', 'Stressed')], max_length=20)),
                ('day_type', models.CharField(choices=[('calm', 'Calm'), ('productive', 'Productive'), ('tired', 'Tired'), ('overwhelmed', 'Overwhelmed'), ('motivated', 'Motivated')], max_length=20)),
                ('distractions', models.JSONField(default=list)),
                ('distraction_time', models.CharField(blank=True, choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening'), ('night', 'Night')], default='', max_length=20)),
                ('habits_completed', models.JSONField(blank=True, default=list)),
                ('reflection_went_well', models.CharField(blank=True, default='', max_length=150)),
                ('reflection_improve_tomorrow', models.CharField(blank=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_checkins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-check_in_date', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'check_in_date'), name='unique_user_daily_checkin'), models.CheckConstraint(condition=models.Q(('study_hours__gte', 0), ('study_hours__lte', 8)), name='checkin_study_hours_between_0_and_8')],
            },
        ),
    ]
