# Generated by Django 5.2.16 on 2026-07-21 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIGenerationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('daily_coach', 'Daily coach'), ('score_explanation', 'Score explanation'), ('goal_coach', 'Goal coach'), ('pattern_discovery', 'Pattern discovery'), ('weekly_coach', 'Weekly coach'), ('journal_ai', 'Journal AI')], max_length=32)),
                ('scope_key', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('cache_hit', 'Cache hit'), ('generated', 'Generated'), ('fallback', 'Deterministic fallback'), ('ineligible', 'Ineligible'), ('throttled', 'Throttled')], max_length=20)),
                ('source', models.CharField(blank=True, default='', max_length=20)),
                ('forced', models.BooleanField(default=False)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_generation_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'service', 'created_at'], name='ai_attempt_user_svc_time_idx')],
            },
        ),
        migrations.CreateModel(
            name='AIInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('daily_coach', 'Daily coach'), ('score_explanation', 'Score explanation'), ('goal_coach', 'Goal coach'), ('pattern_discovery', 'Pattern discovery'), ('weekly_coach', 'Weekly coach'), ('journal_ai', 'Journal AI')], max_length=32)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('scope_key', models.CharField(max_length=100)),
                ('evidence_hash', models.CharField(max_length=64)),
                ('content', models.JSONField(default=dict)),
                ('source', models.CharField(choices=[('llm', 'LLM'), ('fallback', 'Deterministic fallback')], default='fallback', max_length=20)),
                ('model_name', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
                'indexes': [models.Index(fields=['user', 'service', 'scope_key'], name='ai_insight_user_svc_scope_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'service', 'version', 'scope_key', 'evidence_hash'), name='unique_user_service_version_scope_evidence')],
            },
        ),
    ]
